import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Button, Center, Link, SimpleGrid, Text } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Map Case</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Center>
        <SimpleGrid mt={12} columns={2} spacing={10}>
          <Link href={"/add-location"}>
            <Button padding={8} bg="salmon">
              {" "}
              Konum Ekleme Sayfasına Git{" "}
            </Button>
          </Link>

          <Link href={"/list-locations"}>
            <Button padding={8} bg="salmon">
              Lokasyon Listeleme Sayfasına Git
            </Button>
          </Link>

          <Link href={"/make-route"}>
            {" "}
            <Button padding={8} bg="salmon">
              {" "}
              Rota Oluşturma Sayfasına Git{" "}
            </Button>
          </Link>
        </SimpleGrid>
      </Center>
    </>
  );
}
